import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import bgImage from "@/public/background.avif"
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import SmoothScroll from "@/styles/SmoothScroll"; // Sesuaikan path-nya
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Browser Supply Clone",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.avif",
  },
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const gambetta = localFont({
  src: [
    {
      path: "../assets/fonts/Gambetta-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/Gambetta-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Gambetta-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-serif-custom",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${gambetta.variable} h-full antialiased`}
    >
      <body className="min-h-screen text-white relative overflow-x-hidden px-4 sm:px-8 antialiased">
          <SmoothScroll>
          <Navbar/>
          <div className="fixed inset-0 z-0 pointer-events-none opacity-45">
            <div className="absolute top-0 left-0 w-full h-[140vh]">
              <Image
                src={bgImage}
                alt="Top Ambient Background"
                fill
                priority
                placeholder="blur"
                className="object-cover object-top blur-[30px] rotate-180 scale-120"
              />
            </div>
          </div>

          <div className="max-w-7xl mx-auto min-h-screen bg-transparent flex flex-col">
            {children}
          </div>
          
          <Footer/>
        </SmoothScroll>
      </body>
    </html>
  );
}
